name: ocapi
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - et_xmlfile=2.0.0
  - freetype=2.13.3
  - gmp=6.3.0
  - gmpy2=2.2.1
  - humanfriendly=10.0
  - intel-openmp=2025.0.0
  - jpeg=9f
  - lcms2=2.16
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.50
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib-base=3.10.6
  - mkl=2025.0.0
  - mkl-service=2.5.2
  - mkl_fft=2.1.1
  - mkl_random=1.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - numexpr=2.14.1
  - numpy-base=2.3.4
  - onnxruntime=1.22.2
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.0.18
  - pandas=2.3.3
  - pip=24.2
  - pyreadline3=3.5.4
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-flatbuffers=24.3.25
  - python-tzdata=2025.2
  - pytz=2025.2
  - seaborn=0.13.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - sympy=1.14.0
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.14
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - asttokens==2.4.1
      - attrs==24.2.0
      - autoreject==0.4.3
      - certifi==2025.11.12
      - cffi==1.17.1
      - charset-normalizer==3.4.4
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.1.1
      - executing==2.1.0
      - fonttools==4.54.1
      - h5io==0.2.5
      - h5py==3.15.1
      - idna==3.11
      - ipython==8.27.0
      - jax==0.4.33
      - jaxlib==0.4.33
      - jedi==0.19.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markupsafe==3.0.3
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mediapipe==0.10.14
      - ml-dtypes==0.5.0
      - mne==1.11.0
      - mne-icalabel==0.8.1
      - numpy==2.1.1
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.10.0.84
      - opt-einsum==3.4.0
      - packaging==24.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.5.0
      - pooch==1.8.2
      - prompt-toolkit==3.0.48
      - protobuf==4.25.5
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.18.0
      - pymatreader==1.1.0
      - pyparsing==3.1.4
      - pyprep==0.5.0
      - pyyaml==6.0.2
      - requests==2.32.5
      - scikit-learn==1.7.2
      - scipy==1.14.1
      - six==1.16.0
      - sounddevice==0.5.0
      - stack-data==0.6.3
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - xmltodict==1.0.2
