name: ocapi
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - et_xmlfile=1.1.0
  - intel-openmp=2023.1.0
  - joblib=1.4.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - ncurses=6.4
  - numexpr=2.10.1
  - numpy-base=2.0.1
  - openpyxl=3.1.5
  - openssl=1.1.1w
  - pandas=2.2.3
  - python=3.11.0
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2024.1
  - readline=8.2
  - scikit-learn=1.6.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - asttokens==2.4.1
      - attrs==24.2.0
      - cffi==1.17.1
      - colorama==0.4.6
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.1.1
      - executing==2.1.0
      - flatbuffers==24.3.25
      - fonttools==4.54.1
      - ipython==8.27.0
      - jax==0.4.33
      - jaxlib==0.4.33
      - jedi==0.19.1
      - kiwisolver==1.4.7
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mediapipe==0.10.14
      - ml-dtypes==0.5.0
      - numpy==2.1.1
      - opencv-contrib-python==4.10.0.84
      - opencv-python==4.10.0.84
      - opt-einsum==3.4.0
      - packaging==24.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - pip==25.3
      - prompt-toolkit==3.0.48
      - protobuf==4.25.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygments==2.18.0
      - pyparsing==3.1.4
      - pyyaml==6.0.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - setuptools==44.1.1
      - six==1.16.0
      - sounddevice==0.5.0
      - stack-data==0.6.3
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - wcwidth==0.2.13
